### ISSUE TITLE
You rock!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-chicainoportuna#1]
Excellent work, @chicainoportuna!!!!

I don't have any tips to improve the exercise...

Here you are, a Well Done gif:

![Well Done](https://media.giphy.com/media/ywy6GUsqajpY6CuZzg/giphy.gif)

**Comment by chicainoportuna** [comment]
I do have a proposal for improvement, haha! In the other branch I have put the console log correctly inside the functions and it works :)

And... In fact, I tried to get the "approximate" message to affect the 5 previous and subsequent numbers, not just one, but I was not able at the time of the exam. Now I think I do have an idea of ​​how to do it and I think I'll keep improving to practice, I really enjoy this type of exercises!

**Comment by oneeyedman** [comment]
LGTM!!! Let's do that!

But at some point, I will ask you to explain your exercise to the rest of the class. Yay or nay?

**Comment by chicainoportuna** [comment]
Yay! Of course! (But not in english, please xD)
